name: CI

on:

  push:
    branches:
      -main
      
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Format code
        run: npm run code:fix

      - name: Lint code
        run: npm run lint

      - name: Test with coverage
        run: npm test -- --coverage
        env:
          CI: true

      - name: Build
        run: npm run build

      - name: Display success message
        run: echo "PIPELINE SUCCESS WITHOUT ERRORS"
